import { Usuario } from './usuario';
import { RolAsignado } from './rolAsignado';

export const ASIGNACIONES : RolAsignado[] = [
  {
    fechaInicio: '10-02-2019',
    fechaFin: '',
    rol: 'Graficador',
    usuario: {
      nombres: 'Sergio', 
      apellidos: 'Cárdenas',
      email: '',
      tipoIdentificacion: '',
      numeroIdentificacion: '1',
    },
    red: {
      codigo: 'RED001',
      nombre: 'infografía para el curso Educación, Juventud y Drogas',
      nombreCorto: 'infografía drogas',
      descripcion: 'esta es una descripción breve',
      fechaInicio: '10-02-2019',
      fechaCierre: '01-04-2019',
      fechaCreacion: '01-02-2016',
      porcentajeAvance: 80,
      tipo: 'infografía',
      solicitante: 'la profe',
      horasTrabajadas: 50,
      horasEstimadas: 60,
    },
  },
  {
    fechaInicio: '10-02-2019',
    fechaFin: '',
    rol: 'Diseñador',
    usuario: {
      nombres: 'Sergio', 
      apellidos: 'Cárdenas',
      email: '',
      tipoIdentificacion: '',
      numeroIdentificacion: '1',
    },
    red: {
      codigo: 'RED002',
      nombre: 'video para el curso Educación, Juventud y Drogas',
      nombreCorto: 'video drogas',
      descripcion: 'esta es una descripción breve',
      fechaInicio: '25-01-2019',
      fechaCierre: '05-04-2019',
      fechaCreacion: '01-02-2016',
      porcentajeAvance: 90,
      tipo: 'video',
      solicitante: 'la profe',
      horasTrabajadas: 110,
      horasEstimadas: 130,
    },
  },
  {
    fechaInicio: '10-02-2019',
    fechaFin: '',
    rol: 'Diseñador',
    usuario: {
      nombres: 'Jairo', 
      apellidos: 'Ruano',
      email: '',
      tipoIdentificacion: '',
      numeroIdentificacion: '2',
    },
    red: {
      codigo: 'RED001',
      nombre: 'infografía para el curso Educación, Juventud y Drogas',
      nombreCorto: 'infografía drogas',
      descripcion: 'esta es una descripción breve',
      fechaInicio: '10-02-2019',
      fechaCierre: '01-04-2019',
      fechaCreacion: '01-02-2016',
      porcentajeAvance: 80,
      tipo: 'infografía',
      solicitante: 'la profe',
      horasTrabajadas: 50,
      horasEstimadas: 60,
    },
  },
  {
    fechaInicio: '10-02-2019',
    fechaFin: '',
    rol: 'Diseñador',
    usuario: {
      nombres: 'Jairo', 
      apellidos: 'Ruano',
      email: '',
      tipoIdentificacion: '',
      numeroIdentificacion: '2',
    },
    red: {
      codigo: 'RED003',
      nombre: 'animación para el curso Educación, Juventud y Drogas',
      nombreCorto: 'animación drogas',
      descripcion: 'esta es una descripción breve',
      fechaInicio: '25-01-2019',
      fechaCierre: '05-04-2019',
      fechaCreacion: '01-02-2016',
      porcentajeAvance: 50,
      tipo: 'animación',
      solicitante: 'la profe',
      horasTrabajadas: 110,
      horasEstimadas: 130,
    },
  },
]
